---
global: # generall configs effecting one or multiple parts
  assignments:
    split_number: 1 # number of files fastq should be split for parallelization
assignments:
  exampleAssignment: # name of an example assignment (can be any string)
    bc_length: 20
    BC_rev_comp: true
    linker: TCTAGACCGTCACTAACTAACAGTGGGTACCC
    alignment_tool:
      tool: exact # bwa or exact
      configs:
        sequence_length: 170 # sequence length of design excluding adapters.
        alignment_start: 1 # start of the alignment in the reference
    FW:
      - resources/Assignment_BasiC/R1.fastq.gz
    REV:
      - resources/Assignment_BasiC/R3.fastq.gz
    reference: resources/design.fa
    configs:
      default: {} # name of an example filtering config
