---
name: Tests

on:
  push:
    branches: [master, development]
  pull_request:
    branches: [master, development]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: docs/environment.yml
          environment-name: sphinx
      - name: Run sphinx
        shell: bash -l {0}
        run: |
          cd docs && make html
  Formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Formatting
        uses: super-linter/super-linter@v6
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_PYTHON_FLAKE8: true
          PYTHON_FLAKE8_CONFIG_FILE: .flake8
          VALIDATE_JSON: true
          VALIDATE_YAML: true
          YAML_CONFIG_FILE: .yamllint.yml
          VALIDATE_SNAKEMAKE_SNAKEFMT: true
          VALIDATE_R: true

  Linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint workflow
        uses: snakemake/snakemake-github-action@v1
        with:
          directory: .
          snakefile: workflow/Snakefile
          args: "--lint --configfile config/example_config.yaml --config version=$(cat version.txt)"
  # Testing:
  #   runs-on: ubuntu-latest
  #   needs:
  #     - Linting
  #     - Formatting
  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Test workflow
  #       uses: snakemake/snakemake-github-action@v1.24.0
  #       with:
  #         directory: .test
  #         snakefile: workflow/Snakefile
  #         args: "--configfile config/example_config.yaml --use-conda --show-failed-logs --cores 3 --conda-cleanup-pkgs cache"

  #     - name: Test report
  #       uses: snakemake/snakemake-github-action@v1.24.0
  #       with:
  #         directory: .test
  #         snakefile: workflow/Snakefile
  #         args: "--configfile config/example_config.yaml --report report.zip"
